apiVersion: apps/v1
kind: Deployment

metadata:
  name: student-feedback-deployment

spec:

  replicas: 3

  selector:
    matchLabels:
      app: student-feedback

  template:

    metadata:
      labels:
        app: student-feedback

    spec:

      containers:

        - name: student-feedback

          image: dhan01/student-feedback:v2

          ports:
            - containerPort: 80
